AsterixCodecExternalInterfaceDescription: DecoderInterface Class Reference
DecoderInterface Class Reference
#include <DecoderInterface.h>
Public Member Functions
void setSourceDatastream (unsigned char *_ASTERIX_datastream, unsigned long _ASTinput_fileSize)
void printAllDecodedRecordsOnJson (RecordCollection *recordsToPrint)
RecordCollection * startDecodingDatablocks (unsigned char *ASTERIX_datastream, unsigned long *sizeOfDatablocksToParse)
RecordCollection * decodingDatablocksFromFile ()
void releaseAllDecodedRecords (RecordCollection *consumerResult)
Private Member Functions
DecoderInterface ()
DecoderInterface (const DecoderInterface &source)=delete
DecoderInterface & operator= (const DecoderInterface &source)=delete
~DecoderInterface ()
void startDecoderThreads ()
RecordCollection * waitForConsumer ()
Static Private Member Functions
static DecoderInterface * getInstance ()
static void deleteInstance ()
Private Attributes
unsigned char * ASTERIX_datastream
unsigned long ASTinput_fileSize
unsigned long indexInASTERIX_datastream = 0
CommonVariables * common
FacadeCommonVariables * facadeCommon
BlockingQueueManager * bqManager
vector< future< unsigned long long > > parsingResults
vector< DecodedValueObjectPoolManager * > decodedValueOPManagerVector
vector< future< RecordCollection * > > decodingResults
Static Private Attributes
static DecoderInterface * singletonDecoder = nullptr
Friends
class CodecInterface
Detailed Description
Provide access to the encoding functions.
Definition at line 25 of file DecoderInterface.h.
Constructor & Destructor Documentation
DecoderInterface() [1/2]
DecoderInterface::DecoderInterface () private
Constructor.
The API interface is a singleton therefore this method is private.
Definition at line 8 of file DecoderInterface.cpp.
References ASTERIX_datastream, ASTinput_fileSize, bqManager, common, and facadeCommon.
Referenced by getInstance().
DecoderInterface() [2/2]
DecoderInterface::DecoderInterface (const DecoderInterface & source) private delete
Copy constructor.
~DecoderInterface()
DecoderInterface::~DecoderInterface () private
Destructor.
The API interface is a singleton therefore this method is private
Definition at line 16 of file DecoderInterface.cpp.
References bqManager, common, decodedValueOPManagerVector, deleteInstance(), facadeCommon, and singletonDecoder.
Member Function Documentation
decodingDatablocksFromFile()
RecordCollection * DecoderInterface::decodingDatablocksFromFile ()
DECODE - Parse and decode a given number of datablocks (N). The input file is previously stored from the 'setSourceDatastream' method. The method decode N datablocks, after the decoding phase it store the index of the new datablock to read for the next call. If the datablocks in the input file are finished, the methods return nullptr.
Returns
Collection of decoded records
Definition at line 175 of file DecoderInterface.cpp.
References ASTERIX_datastream, ASTinput_fileSize, facadeCommon, indexInASTERIX_datastream, and startDecodingDatablocks().
deleteInstance()
void DecoderInterface::deleteInstance () static private
SETUP - Remove the instance of the Singleton, it is possible only from the CodecInterface class, thanks to the friendship property
Definition at line 53 of file DecoderInterface.cpp.
References singletonDecoder.
Referenced by CodecInterface::releaseMemory(), and ~DecoderInterface().
getInstance()
DecoderInterface * DecoderInterface::getInstance () static private
Provides the instance of the interface to the API. The API is a singleton. DecoderInterface is instantiable only from the CodecInterface class, thanks to the friendship property
Definition at line 46 of file DecoderInterface.cpp.
References DecoderInterface(), and singletonDecoder.
Referenced by CodecInterface::CodecInterface().
operator=()
DecoderInterface& DecoderInterface::operator= (const DecoderInterface & source) private delete
Copy assignment operator.
printAllDecodedRecordsOnJson()
void DecoderInterface::printAllDecodedRecordsOnJson (RecordCollection * recordsToPrint)
DECODE - Prints the decoded records onto a set of JSON files.
Parameters
recordsToPrint Parsed record to be printed
Definition at line 211 of file DecoderInterface.cpp.
References common, RecordCollection::getElementNamesOfARecord(), RecordCollection::getElementValuesOfARecord(), and RecordCollection::getTotalNumberOfRecords().
Referenced by startDecodingDatablocks().
releaseAllDecodedRecords()
void DecoderInterface::releaseAllDecodedRecords (RecordCollection * consumerResult)
Definition at line 96 of file DecoderInterface.cpp.
References decodedValueOPManagerVector.
setSourceDatastream()
void DecoderInterface::setSourceDatastream (unsigned char * _ASTERIX_datastream, unsigned long _ASTinput_fileSize)
SETUP - Store in the DecoderInterface the input for the 'decodingDatablocksFromFile' methods.
Parameters
_ASTERIX_datastream Pointer to the ASTERIX bytestream opened from the client
_ASTinput_fileSize Size in byte of the input ASTERIX file
Definition at line 105 of file DecoderInterface.cpp.
References ASTERIX_datastream, and ASTinput_fileSize.
startDecoderThreads()
void DecoderInterface::startDecoderThreads () private
DECODE - Starts all consumer threads.
Definition at line 61 of file DecoderInterface.cpp.
References decodedValueOPManagerVector, decodingResults, and facadeCommon.
Referenced by startDecodingDatablocks().
startDecodingDatablocks()
RecordCollection * DecoderInterface::startDecodingDatablocks (unsigned char * ASTERIX_datastream, unsigned long * sizeOfDatablocksToParse)
TODO DECODE - Parses the ASTERIX byte stream already loaded into memory.
Parameters
ASTERIX_datastream Pointer to the ASTERIX bytestream into memory
sizeOfDatablocksToParse Size in byte of the input file stream
Returns
Collection of decoded records
Definition at line 110 of file DecoderInterface.cpp.
References bqManager, common, facadeCommon, parsingResults, printAllDecodedRecordsOnJson(), startDecoderThreads(), and waitForConsumer().
Referenced by decodingDatablocksFromFile().
waitForConsumer()
RecordCollection * DecoderInterface::waitForConsumer () private
DECODE - Waits for the completion of all consuming threads.
Returns
Collection of decoded records
Definition at line 78 of file DecoderInterface.cpp.
References RecordCollection::addRecordsInCollection(), and decodingResults.
Referenced by startDecodingDatablocks().
Friends And Related Function Documentation
CodecInterface
friend class CodecInterface friend
Definition at line 26 of file DecoderInterface.h.
Member Data Documentation
ASTERIX_datastream
unsigned char* DecoderInterface::ASTERIX_datastream private
Variable to keep in memory the ASTERIX bytestream
Definition at line 124 of file DecoderInterface.h.
Referenced by DecoderInterface(), decodingDatablocksFromFile(), and setSourceDatastream().
ASTinput_fileSize
unsigned long DecoderInterface::ASTinput_fileSize private
Variable to keep in memory the size in byte of the 'ASTERIX_datastream'
Definition at line 129 of file DecoderInterface.h.
Referenced by DecoderInterface(), decodingDatablocksFromFile(), and setSourceDatastream().
bqManager
BlockingQueueManager* DecoderInterface::bqManager private
Singleton that manage access to the blocking queue for both producer side and consumer side. It is thread safe.
Definition at line 146 of file DecoderInterface.h.
Referenced by DecoderInterface(), startDecodingDatablocks(), and ~DecoderInterface().
common
CommonVariables* DecoderInterface::common private
Pointer to the singleton that manage all common variables, including the parameters set by the user.
Definition at line 139 of file DecoderInterface.h.
Referenced by DecoderInterface(), printAllDecodedRecordsOnJson(), startDecodingDatablocks(), and ~DecoderInterface().
decodedValueOPManagerVector
vector<DecodedValueObjectPoolManager*> DecoderInterface::decodedValueOPManagerVector private
Vector of object pool used only during the decoding phase. Is a collector for results before building a DecoderResult object and return it to the client.
Definition at line 157 of file DecoderInterface.h.
Referenced by releaseAllDecodedRecords(), startDecoderThreads(), and ~DecoderInterface().
decodingResults
vector<future<RecordCollection*> > DecoderInterface::decodingResults private
Variable to collect all results of the DECODER threads (i.e. an object with the decoded records inside).
Definition at line 162 of file DecoderInterface.h.
Referenced by startDecoderThreads(), and waitForConsumer().
facadeCommon
FacadeCommonVariables* DecoderInterface::facadeCommon private
Definition at line 141 of file DecoderInterface.h.
Referenced by DecoderInterface(), decodingDatablocksFromFile(), startDecoderThreads(), startDecodingDatablocks(), and ~DecoderInterface().
indexInASTERIX_datastream
unsigned long DecoderInterface::indexInASTERIX_datastream = 0 private
Main index to move around the 'ASTERIX_datastream' buffer
Definition at line 134 of file DecoderInterface.h.
Referenced by decodingDatablocksFromFile().
parsingResults
vector<future<unsigned long long> > DecoderInterface::parsingResults private
Variable to collect all results of the PARSER threads (i.e. number of parsed records).
Definition at line 151 of file DecoderInterface.h.
Referenced by startDecodingDatablocks().
singletonDecoder
DecoderInterface * DecoderInterface::singletonDecoder = nullptr static private
Singleton private instance
Definition at line 119 of file DecoderInterface.h.
Referenced by deleteInstance(), getInstance(), and ~DecoderInterface().
The documentation for this class was generated from the following files:
facade/DecoderInterface.h
facade/DecoderInterface.cpp