AsterixCodecExternalInterfaceDescription: EncoderInterface Class Reference
EncoderInterface Class Reference
#include <EncoderInterface.h>
Public Member Functions
unsigned char * encodeRecords (RecordCollection *recordsToEncode)
unsigned char * encodeSingleRecord (Record *recordToEncode)
FailureReport * getFinalReport ()
Private Member Functions
void printASTOnFile (unsigned char *ASTERIX_bytestream)
EncoderInterface ()
EncoderInterface (const EncoderInterface &source)=delete
EncoderInterface & operator= (const EncoderInterface &source)=delete
~EncoderInterface ()
Static Private Member Functions
static EncoderInterface * getInstance ()
static void deleteInstance ()
Private Attributes
CommonVariables * common
FacadeCommonVariables * facadeCommon
vector< future< unsigned char * > > encoderResults
ofstream outFile
Static Private Attributes
static EncoderInterface * singletonDecoder = nullptr
Friends
class CodecInterface
Detailed Description
Provide access to the encoding functions.
Definition at line 20 of file EncoderInterface.h.
Constructor & Destructor Documentation
EncoderInterface() [1/2]
EncoderInterface::EncoderInterface () private
Constructor.
The API interface is a singleton therefore this method is private.
Definition at line 7 of file EncoderInterface.cpp.
References common, and facadeCommon.
Referenced by getInstance().
EncoderInterface() [2/2]
EncoderInterface::EncoderInterface (const EncoderInterface & source) private delete
Copy constructor.
~EncoderInterface()
EncoderInterface::~EncoderInterface () private
Destructor.
The API interface is a singleton therefore this method is private
Definition at line 12 of file EncoderInterface.cpp.
References common, deleteInstance(), facadeCommon, and singletonDecoder.
Member Function Documentation
deleteInstance()
void EncoderInterface::deleteInstance () static private
SETUP - Remove the instance of the Singleton, it is possible only from the CodecInterface class, thanks to the friendship property
Definition at line 34 of file EncoderInterface.cpp.
References singletonDecoder.
Referenced by CodecInterface::releaseMemory(), and ~EncoderInterface().
encodeRecords()
unsigned char * EncoderInterface::encodeRecords (RecordCollection * recordsToEncode)
ENCODE - Encode a collection of records giving back to the client a raw bytestream.
Parameters
recordsToEncode Collection of records to encode
Returns
The raw bytestream with the encoded datablocks (one Record for each Datablock). If print on AST file is enabled, it returns nullptr.
Definition at line 41 of file EncoderInterface.cpp.
References common, encoderResults, facadeCommon, RecordCollection::getTotalNumberOfRecords(), outFile, and printASTOnFile().
encodeSingleRecord()
unsigned char * EncoderInterface::encodeSingleRecord (Record * recordToEncode)
ENCODE - Encode a single Record, giving back to the client a raw bytestream.
Parameters
recordToEncode Record to encode
Returns
The raw bytestream with the Datablock hosting the single Record to encode
Definition at line 122 of file EncoderInterface.cpp.
References common, encoderResults, facadeCommon, outFile, and printASTOnFile().
getFinalReport()
FailureReport * EncoderInterface::getFinalReport ()
ENCODE - Return a pointer to the FailureReport object build during the encoding phase.
Definition at line 197 of file EncoderInterface.cpp.
getInstance()
EncoderInterface * EncoderInterface::getInstance () static private
SETUP - Provides the instance of the interface to the API. The API is a singleton. EncoderInterface is instantiable only from the CodecInterface class, thanks to the friendship property
Definition at line 27 of file EncoderInterface.cpp.
References EncoderInterface(), and singletonDecoder.
Referenced by CodecInterface::CodecInterface().
operator=()
EncoderInterface& EncoderInterface::operator= (const EncoderInterface & source) private delete
Copy assignment operator.
printASTOnFile()
void EncoderInterface::printASTOnFile (unsigned char * ASTERIX_bytestream) private
ENCODE - Prints on a .ast file the encoded bytestream.
Parameters
ASTERIX_bytestream Input ASTERIX bytestream to print on the file
Definition at line 192 of file EncoderInterface.cpp.
References outFile.
Referenced by encodeRecords(), and encodeSingleRecord().
Friends And Related Function Documentation
CodecInterface
friend class CodecInterface friend
Definition at line 21 of file EncoderInterface.h.
Member Data Documentation
common
CommonVariables* EncoderInterface::common private
Pointer to the singleton that manage common variables.
Definition at line 96 of file EncoderInterface.h.
Referenced by encodeRecords(), EncoderInterface(), encodeSingleRecord(), and ~EncoderInterface().
encoderResults
vector<future<unsigned char*> > EncoderInterface::encoderResults private
Variable to collect all results of the encoder.
Definition at line 106 of file EncoderInterface.h.
Referenced by encodeRecords(), and encodeSingleRecord().
facadeCommon
FacadeCommonVariables* EncoderInterface::facadeCommon private
Pointer to the singleton that manage common variables shared with DecoderInterface.
Definition at line 101 of file EncoderInterface.h.
Referenced by encodeRecords(), EncoderInterface(), encodeSingleRecord(), and ~EncoderInterface().
outFile
ofstream EncoderInterface::outFile private
File to write all results of the encoder.
Definition at line 111 of file EncoderInterface.h.
Referenced by encodeRecords(), encodeSingleRecord(), and printASTOnFile().
singletonDecoder
EncoderInterface * EncoderInterface::singletonDecoder = nullptr static private
Singleton private instance
Definition at line 91 of file EncoderInterface.h.
Referenced by deleteInstance(), getInstance(), and ~EncoderInterface().
The documentation for this class was generated from the following files:
facade/EncoderInterface.h
facade/EncoderInterface.cpp