AsterixCodecExternalInterfaceDescription: ReturnStatus Class Reference
ReturnStatus Class Reference
#include <ReturnStatus.hpp>
Public Member Functions
ReturnStatus ()
std::string getMessage ()
void setMessage (std::string _message)
ReturnCodes getCode ()
void setCode (ReturnCodes _code)
void clear ()
Private Attributes
std::string message
ReturnCodes code
Detailed Description
Definition at line 13 of file ReturnStatus.hpp.
Constructor & Destructor Documentation
ReturnStatus()
ReturnStatus::ReturnStatus () inline
Default constructor.
Set the code private field to SUCCESS as default value.
Definition at line 20 of file ReturnStatus.hpp.
References code, message, and SUCCESS.
Member Function Documentation
clear()
void ReturnStatus::clear () inline
Sets the code to the default one (SUCCESS by default).
Definition at line 60 of file ReturnStatus.hpp.
References code, message, and SUCCESS.
Referenced by CodecInterface::loadAsterixConfiguration(), CodecInterface::serializeAsterixConfiguration(), and CodecInterface::setUpEnvironment().
getCode()
ReturnCodes ReturnStatus::getCode () inline
Gets the actual value of the code field.
Returns
Actual value of code
Definition at line 45 of file ReturnStatus.hpp.
References code.
getMessage()
std::string ReturnStatus::getMessage () inline
Gets the string message.
Returns
Message
Definition at line 29 of file ReturnStatus.hpp.
References message.
setCode()
void ReturnStatus::setCode (ReturnCodes _code) inline
Sets the current code.
Parameters
_code Enumeration value for the code
Definition at line 53 of file ReturnStatus.hpp.
References code.
Referenced by FailureReport::addFailure(), and CodecInterface::setUpEnvironment().
setMessage()
void ReturnStatus::setMessage (std::string _message) inline
Sets the string message.
Parameters
_message Message to be set
Definition at line 37 of file ReturnStatus.hpp.
References message.
Referenced by FailureReport::addFailure(), and CodecInterface::setUpEnvironment().
Member Data Documentation
code
ReturnCodes ReturnStatus::code private
Enumerator code
Definition at line 74 of file ReturnStatus.hpp.
Referenced by clear(), getCode(), ReturnStatus(), and setCode().
message
std::string ReturnStatus::message private
Textual message
Definition at line 69 of file ReturnStatus.hpp.
Referenced by clear(), getMessage(), ReturnStatus(), and setMessage().
The documentation for this class was generated from the following file:
facade/ReturnStatus.hpp